<?php exit(); /* For security reason. To avoid public user downloading below data! */?>
2012-09-18 00:46:35	190.177.72.131	FormMail
[Email sent]
--------------------------------------------------------------------------------
To: secretaria@eisteddfod.org.ar
Subject: InscripciÃ³n entrante
Email sent
From: "Kevin Roberts" <secretaria@eisteddfod.org.ar>
CC: secretaria@eisteddfod.org.ar, webmaster@eisteddfod.org.ar
MIME-Version: 1.0
Content-type: text/html; charset=UTF-8<html><title>Your Form Mail Content | htttp://phpfmg.sourceforge.net</title><style type='text/css'>body, td{font-family : Verdana, Arial, Helvetica, sans-serif;font-size : 13px;}</style><body><table cellspacing=0 cellpadding=0 border=0 >
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nombre, Seudonimo, o Denominacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Kevin&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Apellido&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Roberts&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nacionalidad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Argentino&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Provincia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chubut&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Ciudad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Trelew&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>DNI&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>36650788&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Fecha de Nacimiento&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>03/03/1992&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Telefono de referencia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>4432294&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Email&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>kevinch3@gmail.com&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Direccion Postal&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Honduras 223&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Competencia a inscribirse&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>005&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Alguna observacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
</table></body></html><br>

--------------------------------------------------------------------------------
2012-09-18 00:50:26	190.177.72.131	FormMail
[Email sent]
--------------------------------------------------------------------------------
To: secretaria@eisteddfod.org.ar
Subject: InscripciÃ³n entrante
Email sent
From: "assaflm Roberts" <secretaria@eisteddfod.org.ar>
CC: secretaria@eisteddfod.org.ar, webmaster@eisteddfod.org.ar
MIME-Version: 1.0
Content-type: text/html; charset=UTF-8<html><title>Your Form Mail Content | htttp://phpfmg.sourceforge.net</title><style type='text/css'>body, td{font-family : Verdana, Arial, Helvetica, sans-serif;font-size : 13px;}</style><body><table cellspacing=0 cellpadding=0 border=0 >
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nombre, Seudonimo, o Denominacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>assaflm&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Apellido&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Roberts&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nacionalidad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Arg&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Provincia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chubut&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Ciudad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Trelew&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>DNI&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>512121&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Fecha de Nacimiento&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>02/02/1914&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Telefono de referencia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>4432294&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Email&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>kevinch3@gmail.com&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Direccion Postal&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Competencia a inscribirse&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>005&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Alguna observacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
</table></body></html><br>

--------------------------------------------------------------------------------
2012-09-18 00:53:15	190.177.72.131	FormMail
[Email sent]
--------------------------------------------------------------------------------
To: secretaria@eisteddfod.org.ar
Subject: InscripciÃ³n entrante
Email sent
From: "Tengo SueÃ±o" <secretaria@eisteddfod.org.ar>
CC: secretaria@eisteddfod.org.ar, webmaster@eisteddfod.org.ar
MIME-Version: 1.0
Content-type: text/html; charset=UTF-8<html><title>Your Form Mail Content | htttp://phpfmg.sourceforge.net</title><style type='text/css'>body, td{font-family : Verdana, Arial, Helvetica, sans-serif;font-size : 13px;}</style><body><table cellspacing=0 cellpadding=0 border=0 >
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nombre, Seudonimo, o Denominacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Tengo&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Apellido&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>SueÃ±o&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nacionalidad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Arg&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Provincia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>No idea&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Ciudad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Ahh!!&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>DNI&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Fecha de Nacimiento&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Telefono de referencia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Email&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>imeil@mgslalg.com&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Direccion Postal&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Competencia a inscribirse&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>005 - Cerdd i blant:&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Alguna observacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Ojos, ja.&nbsp;</td></tr>
</table></body></html><br>

--------------------------------------------------------------------------------
2012-09-18 10:52:06	190.177.101.145	FormMail
[Email sent]
--------------------------------------------------------------------------------
To: secretaria@eisteddfod.org.ar
Subject: InscripciÃ³n entrante
Email sent
From: "Astrid Rhys" <secretaria@eisteddfod.org.ar>
CC: secretaria@eisteddfod.org.ar, webmaster@eisteddfod.org.ar
MIME-Version: 1.0
Content-type: text/html; charset=UTF-8<html><title>Your Form Mail Content | htttp://phpfmg.sourceforge.net</title><style type='text/css'>body, td{font-family : Verdana, Arial, Helvetica, sans-serif;font-size : 13px;}</style><body><table cellspacing=0 cellpadding=0 border=0 >
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nombre, Seudonimo, o Denominacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Astrid&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Apellido&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Rhys&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nacionalidad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Argentina&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Provincia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chubut&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Ciudad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Trelew&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>DNI&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>35383670&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Fecha de Nacimiento&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>27/02/1991&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Telefono de referencia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>4434331&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Email&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>astrid_rhys@hotmail.com&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Direccion Postal&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Pasaje Jujuy 412&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Competencia a inscribirse&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>043 - Unawd agored: Cï¿½n Ysgafn: hunanddewisiad - a elecciï¿½n en galï¿½s.&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Alguna observacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
</table></body></html><br>

--------------------------------------------------------------------------------
2012-09-19 15:25:00	200.63.165.171	FormMail
[Email sent]
--------------------------------------------------------------------------------
To: secretaria@eisteddfod.org.ar
Subject: Inscripción entrante
Email sent
From: "Gaston Carabetta" <secretaria@eisteddfod.org.ar>
CC: secretaria@eisteddfod.org.ar, webmaster@eisteddfod.org.ar
MIME-Version: 1.0
Content-type: text/html; charset=UTF-8<html><title>Your Form Mail Content | htttp://phpfmg.sourceforge.net</title><style type='text/css'>body, td{font-family : Verdana, Arial, Helvetica, sans-serif;font-size : 13px;}</style><body><table cellspacing=0 cellpadding=0 border=0 >
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nombre, Seudonimo, o Denominacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Gaston&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Apellido&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Carabetta&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nacionalidad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Argentino&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Provincia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chubut&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Ciudad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Trelew&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>DNI&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>24134000&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Fecha de Nacimiento&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>22/02/1975&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Telefono de referencia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>0280154590127&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Email&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>gcarabetta@gmail.com&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Direccion Postal&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>9100&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Competencia a inscribirse&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>045 - Solo libre: tema del floklore argentino a libre elección.&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Alguna observacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Estaría faltando que obra voy a interpretar y que te puedan adjuntar la partitura!!!! Abrazo&nbsp;</td></tr>
</table></body></html><br>

--------------------------------------------------------------------------------
2012-09-27 11:12:18	190.176.84.150	FormMail
[Email sent]
--------------------------------------------------------------------------------
To: secretaria@eisteddfod.org.ar
Subject: Inscripción entrante
Email sent
From: "Verónica Soledad Despo" <secretaria@eisteddfod.org.ar>
CC: secretaria@eisteddfod.org.ar, webmaster@eisteddfod.org.ar
MIME-Version: 1.0
Content-type: text/html; charset=UTF-8<html><title>Your Form Mail Content | htttp://phpfmg.sourceforge.net</title><style type='text/css'>body, td{font-family : Verdana, Arial, Helvetica, sans-serif;font-size : 13px;}</style><body><table cellspacing=0 cellpadding=0 border=0 >
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nombre, Seudonimo, o Denominacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Verónica Soledad &nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Apellido&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Despo&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nacionalidad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Argentina&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Provincia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chubut&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Ciudad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Gaiman&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>DNI&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>30008642&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Fecha de Nacimiento&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>11/12/1983&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Telefono de referencia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>(0280)154823132&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Email&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>v.sold@hotmail.com&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Direccion Postal&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>B° 50 viviendas, casa n° 42. Gaiman.&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Competencia a inscribirse&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>091 - [Noveles] Fotografía: Tema: &nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Alguna observacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Ninguna.&nbsp;</td></tr>
</table></body></html><br>

--------------------------------------------------------------------------------
2012-10-04 09:25:01	186.123.135.188	FormMail
[Email sent]
--------------------------------------------------------------------------------
To: secretaria@eisteddfod.org.ar
Subject: Inscripción entrante
Email sent
From: "Cinthia Zamarreño" <secretaria@eisteddfod.org.ar>
CC: secretaria@eisteddfod.org.ar, webmaster@eisteddfod.org.ar
MIME-Version: 1.0
Content-type: text/html; charset=UTF-8<html><title>Your Form Mail Content | htttp://phpfmg.sourceforge.net</title><style type='text/css'>body, td{font-family : Verdana, Arial, Helvetica, sans-serif;font-size : 13px;}</style><body><table cellspacing=0 cellpadding=0 border=0 >
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nombre, Seudonimo, o Denominacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Cinthia&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Apellido&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Zamarreño&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nacionalidad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Argentina&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Provincia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chubut&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Ciudad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Gaiman&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>DNI&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>35383609&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Fecha de Nacimiento&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>10/05/1990&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Telefono de referencia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>0280 154 367250&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Email&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>zam.cinthia@gmail.com&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Direccion Postal&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chacra 237 Bryn Crwn&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Competencia a inscribirse&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>022 - Prif adroddiad: &nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Alguna observacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'> - &nbsp;</td></tr>
</table></body></html><br>

--------------------------------------------------------------------------------
2012-10-04 09:29:10	186.123.135.188	FormMail
[Email sent]
--------------------------------------------------------------------------------
To: secretaria@eisteddfod.org.ar
Subject: Inscripción entrante
Email sent
From: "Cinthia Zamarreño" <secretaria@eisteddfod.org.ar>
CC: secretaria@eisteddfod.org.ar, webmaster@eisteddfod.org.ar
MIME-Version: 1.0
Content-type: text/html; charset=UTF-8<html><title>Your Form Mail Content | htttp://phpfmg.sourceforge.net</title><style type='text/css'>body, td{font-family : Verdana, Arial, Helvetica, sans-serif;font-size : 13px;}</style><body><table cellspacing=0 cellpadding=0 border=0 >
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nombre, Seudonimo, o Denominacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Cinthia&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Apellido&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Zamarreño&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nacionalidad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Argentina&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Provincia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chubut&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Ciudad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Gaiman&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>DNI&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>35383609&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Fecha de Nacimiento&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>10/05/1990&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Telefono de referencia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>0280 154 367250&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Email&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>zam.cinthia@gmail.com&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Direccion Postal&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chacra 237 Bryn Crwn&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Competencia a inscribirse&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>025 - Adrodd i ddysgwyr yn unig: &nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Alguna observacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'> - &nbsp;</td></tr>
</table></body></html><br>

--------------------------------------------------------------------------------
2012-10-04 09:31:39	186.123.135.188	FormMail
[Email sent]
--------------------------------------------------------------------------------
To: secretaria@eisteddfod.org.ar
Subject: Inscripción entrante
Email sent
From: "Cinthia Zamarreño" <secretaria@eisteddfod.org.ar>
CC: secretaria@eisteddfod.org.ar, webmaster@eisteddfod.org.ar
MIME-Version: 1.0
Content-type: text/html; charset=UTF-8<html><title>Your Form Mail Content | htttp://phpfmg.sourceforge.net</title><style type='text/css'>body, td{font-family : Verdana, Arial, Helvetica, sans-serif;font-size : 13px;}</style><body><table cellspacing=0 cellpadding=0 border=0 >
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nombre, Seudonimo, o Denominacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Cinthia &nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Apellido&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Zamarreño&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nacionalidad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Argentina&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Provincia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chubut&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Ciudad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Gaiman&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>DNI&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>35383609&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Fecha de Nacimiento&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>10/05/1990&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Telefono de referencia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>0280 154 367250&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Email&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>zam.cinthia@gmail.com&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Direccion Postal&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chacra 237 Bryn Crwn&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Competencia a inscribirse&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>030 - Principal: &nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Alguna observacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'> - &nbsp;</td></tr>
</table></body></html><br>

--------------------------------------------------------------------------------
2012-10-04 09:33:54	186.123.135.188	FormMail
[Email sent]
--------------------------------------------------------------------------------
To: secretaria@eisteddfod.org.ar
Subject: Inscripción entrante
Email sent
From: "Cinthia Zamarreño" <secretaria@eisteddfod.org.ar>
CC: secretaria@eisteddfod.org.ar, webmaster@eisteddfod.org.ar
MIME-Version: 1.0
Content-type: text/html; charset=UTF-8<html><title>Your Form Mail Content | htttp://phpfmg.sourceforge.net</title><style type='text/css'>body, td{font-family : Verdana, Arial, Helvetica, sans-serif;font-size : 13px;}</style><body><table cellspacing=0 cellpadding=0 border=0 >
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nombre, Seudonimo, o Denominacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Cinthia &nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Apellido&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Zamarreño&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nacionalidad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Argentina&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Provincia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chubut&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Ciudad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Gaiman&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>DNI&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>35383609&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Fecha de Nacimiento&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>10/05/1990&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Telefono de referencia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>0280 154 367250&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Email&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>zam.cinthia@gmail.com&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Direccion Postal&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chacra 237 Bryn Crwn&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Competencia a inscribirse&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>032 - Voz femenina: &nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Alguna observacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'> - &nbsp;</td></tr>
</table></body></html><br>

--------------------------------------------------------------------------------
2012-10-04 09:35:51	186.123.135.188	FormMail
[Email sent]
--------------------------------------------------------------------------------
To: secretaria@eisteddfod.org.ar
Subject: Inscripción entrante
Email sent
From: "Cinthia Zamarreño" <secretaria@eisteddfod.org.ar>
CC: secretaria@eisteddfod.org.ar, webmaster@eisteddfod.org.ar
MIME-Version: 1.0
Content-type: text/html; charset=UTF-8<html><title>Your Form Mail Content | htttp://phpfmg.sourceforge.net</title><style type='text/css'>body, td{font-family : Verdana, Arial, Helvetica, sans-serif;font-size : 13px;}</style><body><table cellspacing=0 cellpadding=0 border=0 >
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nombre, Seudonimo, o Denominacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Cinthia &nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Apellido&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Zamarreño&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nacionalidad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Argentina&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Provincia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chubut&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Ciudad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Gaiman&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>DNI&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>35383609&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Fecha de Nacimiento&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>10/05/1990&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Telefono de referencia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>0280 154 367250&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Email&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>zam.cinthia@gmail.com&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Direccion Postal&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chacra 237 Bryn Crwn&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Competencia a inscribirse&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>033 - Voz femenina: &nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Alguna observacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'> - &nbsp;</td></tr>
</table></body></html><br>

--------------------------------------------------------------------------------
2012-10-04 09:37:37	186.123.135.188	FormMail
[Email sent]
--------------------------------------------------------------------------------
To: secretaria@eisteddfod.org.ar
Subject: Inscripción entrante
Email sent
From: "Cinthia Zamarreño" <secretaria@eisteddfod.org.ar>
CC: secretaria@eisteddfod.org.ar, webmaster@eisteddfod.org.ar
MIME-Version: 1.0
Content-type: text/html; charset=UTF-8<html><title>Your Form Mail Content | htttp://phpfmg.sourceforge.net</title><style type='text/css'>body, td{font-family : Verdana, Arial, Helvetica, sans-serif;font-size : 13px;}</style><body><table cellspacing=0 cellpadding=0 border=0 >
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nombre, Seudonimo, o Denominacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Cinthia &nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Apellido&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Zamarreño&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nacionalidad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Argentina&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Provincia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chubut&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Ciudad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Gaiman&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>DNI&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>35383609&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Fecha de Nacimiento&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>10/05/1990&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Telefono de referencia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>0280 154 367250&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Email&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>zam.cinthia@gmail.com&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Direccion Postal&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chacra237Bryn Crwn&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Competencia a inscribirse&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>042 - Unawd agored: Cân Werin: hunanddewisiad - a elección en galés.&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Alguna observacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'> - &nbsp;</td></tr>
</table></body></html><br>

--------------------------------------------------------------------------------
2012-10-04 09:39:18	186.123.135.188	FormMail
[Email sent]
--------------------------------------------------------------------------------
To: secretaria@eisteddfod.org.ar
Subject: Inscripción entrante
Email sent
From: <secretaria@eisteddfod.org.ar>
CC: secretaria@eisteddfod.org.ar, webmaster@eisteddfod.org.ar
MIME-Version: 1.0
Content-type: text/html; charset=UTF-8<html><title>Your Form Mail Content | htttp://phpfmg.sourceforge.net</title><style type='text/css'>body, td{font-family : Verdana, Arial, Helvetica, sans-serif;font-size : 13px;}</style><body><table cellspacing=0 cellpadding=0 border=0 >
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nombre, Seudonimo, o Denominacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Soraya Griffiths - Cinthia Zamarreño&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Apellido&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nacionalidad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Argentina&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Provincia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chubut&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Ciudad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Gaiman&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>DNI&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Fecha de Nacimiento&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Telefono de referencia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Email&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>zam.cinthia@gmail.com&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Direccion Postal&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Competencia a inscribirse&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>047 - Deuawd agored, merched / dynion / cymysg: Hunnanddewisiad - A elección en galés&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Alguna observacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Obra a elección: Lleucu llwyd&nbsp;</td></tr>
</table></body></html><br>

--------------------------------------------------------------------------------
2012-10-04 09:40:45	186.123.135.188	FormMail
[Email sent]
--------------------------------------------------------------------------------
To: secretaria@eisteddfod.org.ar
Subject: Inscripción entrante
Email sent
From: <secretaria@eisteddfod.org.ar>
CC: secretaria@eisteddfod.org.ar, webmaster@eisteddfod.org.ar
MIME-Version: 1.0
Content-type: text/html; charset=UTF-8<html><title>Your Form Mail Content | htttp://phpfmg.sourceforge.net</title><style type='text/css'>body, td{font-family : Verdana, Arial, Helvetica, sans-serif;font-size : 13px;}</style><body><table cellspacing=0 cellpadding=0 border=0 >
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nombre, Seudonimo, o Denominacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Cinthia Zamarreño - Guillermo Thomas&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Apellido&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nacionalidad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Argentina&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Provincia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Ciudad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Gaiman - La Plata&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>DNI&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Fecha de Nacimiento&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Telefono de referencia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Email&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>zam.cinthia@gmail.com&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Direccion Postal&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Competencia a inscribirse&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>047 - Deuawd agored, merched / dynion / cymysg: Hunnanddewisiad - A elección en galés&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Alguna observacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Obra a elección: Drosom ni&nbsp;</td></tr>
</table></body></html><br>

--------------------------------------------------------------------------------
2012-10-04 09:43:36	186.123.135.188	FormMail
[Email sent]
--------------------------------------------------------------------------------
To: secretaria@eisteddfod.org.ar
Subject: Inscripción entrante
Email sent
From: <secretaria@eisteddfod.org.ar>
CC: secretaria@eisteddfod.org.ar, webmaster@eisteddfod.org.ar
MIME-Version: 1.0
Content-type: text/html; charset=UTF-8<html><title>Your Form Mail Content | htttp://phpfmg.sourceforge.net</title><style type='text/css'>body, td{font-family : Verdana, Arial, Helvetica, sans-serif;font-size : 13px;}</style><body><table cellspacing=0 cellpadding=0 border=0 >
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nombre, Seudonimo, o Denominacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Florencia Zamarreño - Cinthia Zamarreño&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Apellido&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nacionalidad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Argentina&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Provincia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chubut&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Ciudad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Gaiman&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>DNI&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Fecha de Nacimiento&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Telefono de referencia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Email&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>zam.cinthia@gmail.com&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Direccion Postal&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Competencia a inscribirse&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>071 - Dúo instrumental: Obra folklórica a elección&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Alguna observacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
</table></body></html><br>

--------------------------------------------------------------------------------
2012-10-04 10:50:06	190.177.105.42	FormMail
[Email sent]
--------------------------------------------------------------------------------
To: secretaria@eisteddfod.org.ar
Subject: Inscripción entrante
Email sent
From: "Kevin Roberts" <secretaria@eisteddfod.org.ar>
CC: secretaria@eisteddfod.org.ar, webmaster@eisteddfod.org.ar
MIME-Version: 1.0
Content-type: text/html; charset=UTF-8<html><title>Your Form Mail Content | htttp://phpfmg.sourceforge.net</title><style type='text/css'>body, td{font-family : Verdana, Arial, Helvetica, sans-serif;font-size : 13px;}</style><body><table cellspacing=0 cellpadding=0 border=0 >
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nombre, Seudonimo, o Denominacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Kevin&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Apellido&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Roberts&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Nacionalidad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Argentino&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Provincia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Chubut&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Ciudad&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>Trelew&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>DNI&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Fecha de Nacimiento&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Telefono de referencia&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Email&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>kevinch3@gmail.com&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Direccion Postal&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>&nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Competencia a inscribirse&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>029 - Voz masculina: &nbsp;</td></tr>
<tr> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;width:33%;border-right:1px solid #cccccc;'>Alguna observacion&nbsp;</td> <td valign=top style='font-family:Verdana, Arial, Helvetica, sans-serif; font-size : 13px; color:#474747;padding:6px;border-bottom:1px solid #cccccc;;'>ESTOY PROBANDO&nbsp;</td></tr>
</table></body></html><br>

--------------------------------------------------------------------------------
